package blocktemplatebuilder

import (
	"fmt"
	"math"
	"sort"
	"strings"

	consensusexternalapi "github.com/cryptix-network/cryptixd/domain/consensus/model/externalapi"
	"github.com/cryptix-network/cryptixd/domain/consensus/processes/coinbasemanager"
	"github.com/cryptix-network/cryptixd/domain/consensus/ruleerrors"
	"github.com/cryptix-network/cryptixd/domain/consensus/utils/atomicstate"
	"github.com/cryptix-network/cryptixd/domain/consensus/utils/consensushashing"
	"github.com/cryptix-network/cryptixd/domain/consensus/utils/merkle"
	"github.com/cryptix-network/cryptixd/domain/consensus/utils/subnetworks"
	"github.com/cryptix-network/cryptixd/domain/consensus/utils/transactionhelper"
	"github.com/cryptix-network/cryptixd/domain/consensusreference"
	miningmanagerapi "github.com/cryptix-network/cryptixd/domain/miningmanager/model"
	"github.com/cryptix-network/cryptixd/util"
	"github.com/cryptix-network/cryptixd/util/difficulty"
	"github.com/cryptix-network/cryptixd/util/mstime"
	"github.com/pkg/errors"
)

const maxBlockTemplateInvalidTransactionRetries = 4

type candidateTx struct {
	*consensusexternalapi.DomainTransaction
	txValue  float64
	gasLimit uint64

	p     float64
	start float64
	end   float64

	isMarkedForDeletion bool
}

// blockTemplateBuilder creates block templates for a miner to consume
type blockTemplateBuilder struct {
	consensusReference consensusreference.ConsensusReference
	mempool            miningmanagerapi.Mempool
	policy             policy

	coinbasePayloadScriptPublicKeyMaxLength uint8
}

// New creates a new blockTemplateBuilder
func New(consensusReference consensusreference.ConsensusReference, mempool miningmanagerapi.Mempool,
	blockMaxMass uint64, minimumRelayTransactionFee util.Amount, coinbasePayloadScriptPublicKeyMaxLength uint8) miningmanagerapi.BlockTemplateBuilder {
	return &blockTemplateBuilder{
		consensusReference: consensusReference,
		mempool:            mempool,
		policy: policy{
			BlockMaxMass:                    blockMaxMass,
			PayloadSoftCapPerBlockBytes:     defaultPayloadSoftCapPerBlockBytes,
			PayloadOvercapFeerateMultiplier: defaultPayloadOvercapFeerateMultiplier,
			MinimumRelayFeerate:             float64(minimumRelayTransactionFee) / 1000.0,
		},

		coinbasePayloadScriptPublicKeyMaxLength: coinbasePayloadScriptPublicKeyMaxLength,
	}
}

// BuildBlockTemplate creates a block template for a miner to consume
// BuildBlockTemplate returns a new block template that is ready to be solved
// using the transactions from the passed transaction source pool and a coinbase
// that either pays to the passed address if it is not nil, or a coinbase that
// is redeemable by anyone if the passed address is nil. The nil address
// functionality is useful since there are cases such as the getblocktemplate
// RPC where external mining software is responsible for creating their own
// coinbase which will replace the one generated for the block template. Thus
// the need to have configured address can be avoided.
//
// The transactions selected and included are prioritized according to several
// factors. First, each transaction has a priority calculated based on its
// value, age of inputs, and size. Transactions which consist of larger
// amounts, older inputs, and small sizes have the highest priority. Second, a
// fee per kilobyte is calculated for each transaction. Transactions with a
// higher fee per kilobyte are preferred. Finally, the block generation related
// policy settings are all taken into account.
//
// Transactions which only spend outputs from other transactions already in the
// block DAG are immediately added to a priority queue which either
// prioritizes based on the priority (then fee per kilobyte) or the fee per
// kilobyte (then priority) depending on whether or not the BlockPrioritySize
// policy setting allots space for high-priority transactions. Transactions
// which spend outputs from other transactions in the source pool are added to a
// dependency map so they can be added to the priority queue once the
// transactions they depend on have been included.
//
// Once the high-priority area (if configured) has been filled with
// transactions, or the priority falls below what is considered high-priority,
// the priority queue is updated to prioritize by fees per kilobyte (then
// priority).
//
// When the fees per kilobyte drop below the TxMinFreeFee policy setting, the
// transaction will be skipped unless the BlockMinSize policy setting is
// nonzero, in which case the block will be filled with the low-fee/free
// transactions until the block size reaches that minimum size.
//
// Any transactions which would cause the block to exceed the BlockMaxMass
// policy setting, exceed the maximum allowed signature operations per block, or
// otherwise cause the block to be invalid are skipped.
//
// Given the above, a block generated by this function is of the following form:
//
//   -----------------------------------  --  --
//  |      Coinbase Transaction         |   |   |
//  |-----------------------------------|   |   |
//  |                                   |   |   | ----- policy.BlockPrioritySize
//  |   High-priority Transactions      |   |   |
//  |                                   |   |   |
//  |-----------------------------------|   | --
//  |                                   |   |
//  |                                   |   |
//  |                                   |   |--- policy.BlockMaxMass
//  |  Transactions prioritized by fee  |   |
//  |  until <= policy.TxMinFreeFee     |   |
//  |                                   |   |
//  |                                   |   |
//  |                                   |   |
//  |-----------------------------------|   |
//  |  Low-fee/Non high-priority (free) |   |
//  |  transactions (while block size   |   |
//  |  <= policy.BlockMinSize)          |   |
//   -----------------------------------  --

func (btb *blockTemplateBuilder) BuildBlockTemplate(
	coinbaseData *consensusexternalapi.DomainCoinbaseData) (*consensusexternalapi.DomainBlockTemplate, error) {
	var lastInvalidTxsErr ruleerrors.ErrInvalidTransactionsInNewBlock
	excludedMissingInputTxs := map[consensusexternalapi.DomainTransactionID]struct{}{}
	for attempt := 0; attempt <= maxBlockTemplateInvalidTransactionRetries; attempt++ {
		blockTemplate, invalidTxsErr, err := btb.buildBlockTemplateOnce(coinbaseData, excludedMissingInputTxs)
		if err == nil {
			return blockTemplate, nil
		}
		if invalidTxsErr == nil {
			return nil, err
		}

		lastInvalidTxsErr = *invalidTxsErr
		removableInvalidTxs, missingInputTxs := splitTemplateInvalidTransactions(invalidTxsErr, excludedMissingInputTxs)

		if len(missingInputTxs) > 0 {
			log.Debugf(
				"Block template skipped missing-input mempool candidates for this template only: attempt=%d/%d txs=%v; keeping them in mempool for orphan/reorg/parallel-template resolution",
				attempt+1,
				maxBlockTemplateInvalidTransactionRetries+1,
				missingInputTxs,
			)
		}
		if len(removableInvalidTxs.InvalidTransactions) > 0 {
			log.Warnf(
				"Block template discarded invalid mempool transaction candidates: attempt=%d/%d invalid_txs=%s; removing from mempool and rebuilding",
				attempt+1,
				maxBlockTemplateInvalidTransactionRetries+1,
				formatInvalidTransactionsForLog(removableInvalidTxs),
			)
			if removeErr := btb.mempool.RemoveInvalidTransactions(removableInvalidTxs); removeErr != nil {
				log.Warnf("Failed removing invalid block-template transactions from mempool: %+v", removeErr)
				return nil, removeErr
			}
		}
	}

	return nil, errors.Errorf(
		"failed to build block template after removing stale/invalid mempool candidates: invalid_txs=%s",
		formatInvalidTransactionsForLog(&lastInvalidTxsErr),
	)
}

func (btb *blockTemplateBuilder) buildBlockTemplateOnce(
	coinbaseData *consensusexternalapi.DomainCoinbaseData,
	excludedTxIDs map[consensusexternalapi.DomainTransactionID]struct{},
) (
	*consensusexternalapi.DomainBlockTemplate,
	*ruleerrors.ErrInvalidTransactionsInNewBlock,
	error,
) {

	mempoolTransactions := btb.mempool.BlockCandidateTransactions()
	candidateTxs := make([]*candidateTx, 0, len(mempoolTransactions))
	for _, tx := range mempoolTransactions {
		if _, excluded := excludedTxIDs[*consensushashing.TransactionID(tx)]; excluded {
			continue
		}
		// Calculate the tx value
		gasLimit := uint64(0)
		if !subnetworks.IsBuiltInOrNative(tx.SubnetworkID) && !subnetworks.IsPayload(tx.SubnetworkID) {
			log.Warnf("Skipping transaction from unsupported subnetwork %s while building a block template", tx.SubnetworkID)
			continue
		}
		candidateTxs = append(candidateTxs, &candidateTx{
			DomainTransaction: tx,
			txValue:           btb.calcTxValue(tx),
			gasLimit:          gasLimit,
		})
	}
	candidatePayloadTxs := countPayloadCandidateTransactions(candidateTxs)
	if candidatePayloadTxs > 0 {
		log.Debugf("Block template sees payload/CAT candidates: total_candidates=%d payload_candidates=%d",
			len(candidateTxs), candidatePayloadTxs)
	}

	// Sort the candidate txs by subnetworkID.
	sort.Slice(candidateTxs, func(i, j int) bool {
		return subnetworks.Less(candidateTxs[i].SubnetworkID, candidateTxs[j].SubnetworkID)
	})
	candidateTxs = keepCATNonceFrontier(candidateTxs)

	log.Debugf("Considering %d transactions for inclusion to new block",
		len(candidateTxs))

	blockTxs := btb.selectTransactions(candidateTxs)
	selectedPayloadTxs := countPayloadTransactions(blockTxs.selectedTxs)
	if candidatePayloadTxs > 0 {
		if selectedPayloadTxs == 0 {
			log.Warnf("Block template did not select any payload/CAT candidates: total_candidates=%d payload_candidates=%d total_selected=%d",
				len(candidateTxs), candidatePayloadTxs, len(blockTxs.selectedTxs))
		} else {
			log.Debugf("Block template selected payload/CAT transactions: payload_selected=%d total_selected=%d txs=%v",
				selectedPayloadTxs, len(blockTxs.selectedTxs), payloadTransactionIDs(blockTxs.selectedTxs))
		}
	}
	blockTemplate, err := btb.consensusReference.Consensus().BuildBlockTemplate(coinbaseData, blockTxs.selectedTxs)

	invalidTxsErr := ruleerrors.ErrInvalidTransactionsInNewBlock{}
	if errors.As(err, &invalidTxsErr) {
		return nil, &invalidTxsErr, err
	}

	if err != nil {
		return nil, nil, err
	}

	log.Debugf("Created new block template (%d transactions, %d in fees, %d mass, target difficulty %064x)",
		len(blockTemplate.Block.Transactions), blockTxs.totalFees, blockTxs.totalMass, difficulty.CompactToBig(blockTemplate.Block.Header.Bits()))

	return blockTemplate, nil, nil
}

func keepCATNonceFrontier(candidateTxs []*candidateTx) []*candidateTx {
	frontierByKey := make(map[string]*candidateTx)
	result := make([]*candidateTx, 0, len(candidateTxs))
	for _, candidate := range candidateTxs {
		key, nonce, ok := catNonceFrontierKey(candidate.DomainTransaction)
		if !ok {
			result = append(result, candidate)
			continue
		}
		current := frontierByKey[key]
		if current == nil {
			frontierByKey[key] = candidate
			continue
		}
		_, currentNonce, _ := catNonceFrontierKey(current.DomainTransaction)
		if nonce < currentNonce {
			frontierByKey[key] = candidate
		}
	}
	for _, candidate := range candidateTxs {
		key, _, ok := catNonceFrontierKey(candidate.DomainTransaction)
		if !ok {
			continue
		}
		if frontierByKey[key] == candidate {
			result = append(result, candidate)
		}
	}
	return result
}

func catNonceFrontierKey(tx *consensusexternalapi.DomainTransaction) (string, uint64, bool) {
	if tx == nil || !subnetworks.IsPayload(tx.SubnetworkID) || len(tx.Payload) == 0 {
		return "", 0, false
	}
	parsed, err := atomicstate.ParsePayload(tx.Payload)
	if err != nil || parsed == nil {
		return "", 0, false
	}
	authInputIndex := int(parsed.AuthInputIndex)
	if authInputIndex >= len(tx.Inputs) || tx.Inputs[authInputIndex] == nil || tx.Inputs[authInputIndex].UTXOEntry == nil {
		return "", 0, false
	}
	ownerID, ok := atomicstate.OwnerIDFromScript(tx.Inputs[authInputIndex].UTXOEntry.ScriptPublicKey())
	if !ok {
		return "", 0, false
	}
	nonceKey, ok := catNonceKey(parsed, ownerID)
	if !ok {
		return "", 0, false
	}
	return fmt.Sprintf("%x:%d:%x", nonceKey.OwnerID, nonceKey.ScopeKind, nonceKey.ScopeID), parsed.Nonce, true
}

func catNonceKey(parsed *atomicstate.ParsedPayload, ownerID [consensusexternalapi.DomainHashSize]byte) (atomicstate.NonceKey, bool) {
	switch op := parsed.Op.(type) {
	case atomicstate.CreateAssetOp, atomicstate.CreateAssetWithMintOp, atomicstate.CreateLiquidityAssetOp:
		return atomicstate.OwnerNonceKey(ownerID), true
	case atomicstate.TransferOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	case atomicstate.MintOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	case atomicstate.BurnOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	case atomicstate.BuyLiquidityExactInOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	case atomicstate.SellLiquidityExactInOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	case atomicstate.ClaimLiquidityFeesOp:
		return atomicstate.AssetNonceKey(ownerID, op.AssetID), true
	default:
		return atomicstate.NonceKey{}, false
	}
}

func splitTemplateInvalidTransactions(
	invalidTxsErr *ruleerrors.ErrInvalidTransactionsInNewBlock,
	excludedMissingInputTxs map[consensusexternalapi.DomainTransactionID]struct{},
) (*ruleerrors.ErrInvalidTransactionsInNewBlock, []string) {
	removableInvalidTxs := &ruleerrors.ErrInvalidTransactionsInNewBlock{}
	missingInputTxs := make([]string, 0)
	if invalidTxsErr == nil {
		return removableInvalidTxs, missingInputTxs
	}

	for _, invalidTx := range invalidTxsErr.InvalidTransactions {
		if invalidTx.Transaction == nil {
			removableInvalidTxs.InvalidTransactions = append(removableInvalidTxs.InvalidTransactions, invalidTx)
			continue
		}

		txID := consensushashing.TransactionID(invalidTx.Transaction)
		var missingTxOut ruleerrors.ErrMissingTxOut
		if errors.As(invalidTx.Error, &missingTxOut) {
			if excludedMissingInputTxs != nil {
				excludedMissingInputTxs[*txID] = struct{}{}
			}
			missingInputTxs = append(missingInputTxs, txID.String())
			continue
		}

		removableInvalidTxs.InvalidTransactions = append(removableInvalidTxs.InvalidTransactions, invalidTx)
	}

	return removableInvalidTxs, missingInputTxs
}

func formatInvalidTransactionsForLog(err *ruleerrors.ErrInvalidTransactionsInNewBlock) string {
	if err == nil || len(err.InvalidTransactions) == 0 {
		return "[]"
	}
	parts := make([]string, 0, len(err.InvalidTransactions))
	for _, invalid := range err.InvalidTransactions {
		txID := "<nil>"
		if invalid.Transaction != nil {
			txID = consensushashing.TransactionID(invalid.Transaction).String()
		}
		parts = append(parts, fmt.Sprintf("%s:%s", txID, invalid.Error))
	}
	return fmt.Sprintf("[%s]", strings.Join(parts, ", "))
}

func countPayloadTransactions(txs []*consensusexternalapi.DomainTransaction) int {
	count := 0
	for _, tx := range txs {
		if subnetworks.IsPayload(tx.SubnetworkID) && len(tx.Payload) > 0 {
			count++
		}
	}
	return count
}

func countPayloadCandidateTransactions(txs []*candidateTx) int {
	count := 0
	for _, tx := range txs {
		if subnetworks.IsPayload(tx.SubnetworkID) && len(tx.Payload) > 0 {
			count++
		}
	}
	return count
}

func payloadTransactionIDs(txs []*consensusexternalapi.DomainTransaction) []string {
	ids := make([]string, 0)
	for _, tx := range txs {
		if subnetworks.IsPayload(tx.SubnetworkID) && len(tx.Payload) > 0 {
			ids = append(ids, consensushashing.TransactionID(tx).String())
		}
	}
	return ids
}

// ModifyBlockTemplate modifies an existing block template to the requested coinbase data and updates the timestamp
func (btb *blockTemplateBuilder) ModifyBlockTemplate(newCoinbaseData *consensusexternalapi.DomainCoinbaseData,
	blockTemplateToModify *consensusexternalapi.DomainBlockTemplate) (*consensusexternalapi.DomainBlockTemplate, error) {

	// The first transaction is always the coinbase transaction
	coinbaseTx := blockTemplateToModify.Block.Transactions[transactionhelper.CoinbaseTransactionIndex]
	newPayload, err := coinbasemanager.ModifyCoinbasePayload(coinbaseTx.Payload, newCoinbaseData, btb.coinbasePayloadScriptPublicKeyMaxLength)
	if err != nil {
		return nil, err
	}
	coinbaseTx.Payload = newPayload
	if blockTemplateToModify.CoinbaseHasRedReward {
		// The last output is always the coinbase red blocks reward
		coinbaseTx.Outputs[len(coinbaseTx.Outputs)-1].ScriptPublicKey = newCoinbaseData.ScriptPublicKey
	}
	// Update the hash merkle root according to the modified transactions
	mutableHeader := blockTemplateToModify.Block.Header.ToMutable()
	// TODO: can be optimized to O(log(#transactions)) by caching the whole merkle tree in BlockTemplate and changing only the relevant path
	mutableHeader.SetHashMerkleRoot(merkle.CalculateHashMerkleRoot(blockTemplateToModify.Block.Transactions))

	newTimestamp := mstime.Now().UnixMilliseconds()
	if newTimestamp >= mutableHeader.TimeInMilliseconds() {
		// Only if new time stamp is later than current, update the header. Otherwise,
		// we keep the previous time as built by internal consensus median time logic
		mutableHeader.SetTimeInMilliseconds(newTimestamp)
	}

	blockTemplateToModify.Block.Header = mutableHeader.ToImmutable()
	blockTemplateToModify.CoinbaseData = newCoinbaseData

	return blockTemplateToModify, nil
}

// calcTxValue calculates a value to be used in transaction selection.
// The higher the number the more likely it is that the transaction will be
// included in the block.
func (btb *blockTemplateBuilder) calcTxValue(tx *consensusexternalapi.DomainTransaction) float64 {
	massLimit := btb.policy.BlockMaxMass

	mass := tx.Mass
	fee := tx.Fee
	if subnetworks.IsBuiltInOrNative(tx.SubnetworkID) {
		return float64(fee) / (float64(mass) / float64(massLimit))
	}
	// TODO: Replace with real gas once implemented
	gasLimit := uint64(math.MaxUint64)
	return float64(fee) / (float64(mass)/float64(massLimit) + float64(tx.Gas)/float64(gasLimit))
}
